---
# Konfigurasi Auto-Deployment cPanel Git Version Control Jagoan Hosting
deployment:
  tasks:
    - export DEPLOYPATH=/home/bprsmadi/bpr-syariah-madinah-test
    - cd $DEPLOYPATH
    - chmod +x deploy.sh
    - ./deploy.sh
